import { useRecommendations } from '../../hooks/useRecommendations';
import type { RecommendationImpact } from '../../types/api';
import { DashboardSection } from '../DashboardSection/DashboardSection';
import { ErrorBanner } from '../ErrorBanner/ErrorBanner';
import { LoadingSpinner } from '../LoadingSpinner/LoadingSpinner';
import styles from './RecommendationsSection.module.css';

interface RecommendationsSectionProps {
  analysisId: number;
}

const IMPACT_CLASS: Record<RecommendationImpact, string> = {
  LOW: styles.impactLow,
  MEDIUM: styles.impactMedium,
  HIGH: styles.impactHigh,
};

function formatCategory(value: string): string {
  return value
    .replace(/_/g, ' ')
    .toLowerCase()
    .replace(/\b\w/g, (char) => char.toUpperCase());
}

export function RecommendationsSection({ analysisId }: RecommendationsSectionProps) {
  const { state, report, error, generate, reset } = useRecommendations();

  return (
    <DashboardSection
      title="AI Recommendations"
      subtitle="Prioritized engineering recommendations generated by the AI Planning Agent from every agent's findings"
    >
      {state === 'idle' && (
        <div className={styles.cta}>
          <p className={styles.ctaText}>
            Ask the AI Planning Agent to interpret the findings above and produce a
            prioritized action plan. It uses the analysis already completed above — no
            re-analysis required.
          </p>
          <button
            type="button"
            className={styles.generateButton}
            onClick={() => generate(analysisId)}
          >
            Generate AI Recommendations
          </button>
        </div>
      )}

      {state === 'loading' && (
        <div className={styles.loading} role="status">
          <LoadingSpinner size="lg" />
          <p className={styles.loadingText}>
            Consolidating findings and generating recommendations…
          </p>
        </div>
      )}

      {state === 'error' && error && (
        <div className={styles.errorWrapper}>
          <ErrorBanner
            title="Could not generate recommendations"
            message={error}
            onDismiss={reset}
          />
          <button
            type="button"
            className={styles.generateButton}
            onClick={() => generate(analysisId)}
          >
            Try Again
          </button>
        </div>
      )}

      {state === 'success' && report && (
        <div className={styles.results}>
          {report.overallAssessment && (
            <div className={styles.assessment}>
              <p className={styles.assessmentLabel}>Overall Assessment</p>
              <p className={styles.assessmentText}>{report.overallAssessment}</p>
            </div>
          )}

          {report.recommendations.length === 0 ? (
            <div className={styles.empty}>
              No recommendations were generated — the analyzed findings did not warrant
              any prioritized action.
            </div>
          ) : (
            <ol className={styles.list}>
              {report.recommendations.map((recommendation) => (
                <li
                  key={`${recommendation.priority}-${recommendation.title}`}
                  className={styles.card}
                >
                  <div className={styles.cardHeader}>
                    <span className={styles.priority}>#{recommendation.priority}</span>
                    <h3 className={styles.cardTitle}>{recommendation.title}</h3>
                    <span
                      className={`${styles.impact} ${IMPACT_CLASS[recommendation.impact]}`}
                    >
                      {recommendation.impact} impact
                    </span>
                  </div>

                  <p className={styles.description}>{recommendation.description}</p>

                  {recommendation.reason && (
                    <p className={styles.reason}>
                      <span className={styles.reasonLabel}>Why</span>
                      {recommendation.reason}
                    </p>
                  )}

                  {recommendation.affectedCategories.length > 0 && (
                    <div className={styles.categories}>
                      {recommendation.affectedCategories.map((category) => (
                        <span key={category} className={styles.category}>
                          {formatCategory(category)}
                        </span>
                      ))}
                    </div>
                  )}
                </li>
              ))}
            </ol>
          )}
        </div>
      )}
    </DashboardSection>
  );
}
