spring.application.name=CodeSentinel

spring.datasource.url=jdbc:postgresql://localhost:5432/codesentinel
spring.datasource.username=codesentinel_user
spring.datasource.password=codesentinel

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

codesentinel.clone.base-path=/tmp/codesentinel